---

- name: RedHat | Install dependencies packages
  yum: name={{ item }} state=installed
  with_items: mongodb_packages_dependencies

- name: RedHat | Add source sources
  template: src=mongodb.repo.j2 dest=/etc/yum.repos.d/mongodb.repo

- name: RedHat | Install Packages
  yum: name={{ item }} state=installed
  with_items: mongodb_packages

- name: MongoDB smallFiles
  copy: src=mongodb.conf dest=/etc/
  tags:
    - mono

- name: MongoDB restart
  service: name=mongod state=restarted
  tags:
    - mono

- name: mongo ports open on firewallD
  firewalld: port={{ item }} permanent=true state=enabled
  with_items:
    - 27017/tcp
    - 27017/udp
